### ISSUE TITLE
align ion torrent amplicon reads to HPV16 graph

### ISSUE THREAD

**Issue by davidroberson** [edawson/hpv_minION_analysis#2]

**Comment by edawson** [comment]
We can now map to HPV16 variation graphs:
`vg map -t 4 -f nci_reads.fastq -x hpv.xg -g hpv.gcsa > alignments.gam`

This has been possible since we began but now a bunch of things have happened:
- Erik has added a MEM (maximal exact matches) mapping algorithm and parameter tuned it for speed and accuracy. It is much better than the old kmer-based mapper.
- I put in a basic set of filtering tools for alignments, so we can filter out some of the low-depth or low-quality alignments. This should give us better calls in the face of the ridiculous effects of error rate we've been seeing (more details later).
- These alignments can now be vectorized and used as input to vowel-wabbit, a machine learning program.
- The (admittedly limited) simulations I've done show it works pretty well.

I'll go ahead and close this, but I'll open another issue with an update.
